alias powermode='sudo auto-cpufreq --force performance'
alias batterymode='sudo auto-cpufreq --force powersave'
alias powerst='sudo auto-cpufreq --force reset'
alias netcp='rsync -avhz --info=progress2'
alias tailup='sudo tailscale up'
alias taildn='sudo tailscale down'
alias pi='ssh kyrotron@pi -p 22'
alias dnfupd='sudo dnf update'
alias sysup='sudo dnf upgrade --refresh -y && sudo dnf autoremove -y'